/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../index";

/**
 * @example
 *     {
 *         watchIndex: "string"
 *     }
 */
export interface GetProfileRequest {
    watchIndex?: Tivet.WatchQuery;
}
