/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../index";

/**
 * @example
 *     {
 *         existingIdentityToken: "string"
 *     }
 */
export interface SetupRequest {
    existingIdentityToken?: Tivet.Jwt;
}
