/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../index";

/**
 * @example
 *     {
 *         status: "online"
 *     }
 */
export interface UpdateStatusRequest {
    status: Tivet.identity.Status;
}
