/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../index";

/**
 * @example
 *     {
 *         displayName: "string",
 *         accountNumber: 1,
 *         bio: "string"
 *     }
 */
export interface ValidateProfileRequest {
    displayName?: Tivet.DisplayName;
    accountNumber?: Tivet.AccountNumber;
    bio?: Tivet.Bio;
}
