/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../../../index";

/**
 * @example
 *     {
 *         project: "string",
 *         environment: "string",
 *         body: {
 *             tags: {
 *                 "key": "value"
 *             },
 *             exclusiveTags: ["string"]
 *         }
 *     }
 */
export interface PatchBuildTagsRequestQuery {
    project?: string;
    environment?: string;
    body: Tivet.actor.PatchBuildTagsRequest;
}
