/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as Tivet from "../../../index";

export class RateLimitError extends errors.TivetError {
    constructor(body: Tivet.ErrorBody) {
        super({
            message: "RateLimitError",
            statusCode: 429,
            body: body,
        });
        Object.setPrototypeOf(this, RateLimitError.prototype);
    }
}
