/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as Tivet from "../../../index";

export class UnauthorizedError extends errors.TivetError {
    constructor(body: Tivet.ErrorBody) {
        super({
            message: "UnauthorizedError",
            statusCode: 408,
            body: body,
        });
        Object.setPrototypeOf(this, UnauthorizedError.prototype);
    }
}
