/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as Tivet from "../../../index";

export class InternalError extends errors.TivetError {
    constructor(body: Tivet.ErrorBody) {
        super({
            message: "InternalError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalError.prototype);
    }
}
