/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TivetEnvironment = {
    Production: "https://api.tivet.gg",
} as const;

export type TivetEnvironment = typeof TivetEnvironment.Production;
