/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../../../../../index";

/**
 * @example
 *     {
 *         deviceLinkToken: "string",
 *         watchIndex: "string"
 *     }
 */
export interface GetDeviceLinkRequest {
    deviceLinkToken: Tivet.Jwt;
    watchIndex?: Tivet.WatchQuery;
}
