/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../index";

/**
 * @example
 *     {
 *         project: "string",
 *         environment: "string",
 *         endpointType: "hostname"
 *     }
 */
export interface ListActorsRequestQuery {
    project?: string;
    environment?: string;
    endpointType?: Tivet.actor.EndpointType;
}
