/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../../../index";

/**
 * @example
 *     {
 *         origin: "string",
 *         gameModes: ["string"],
 *         regions: ["string"],
 *         preventAutoCreateLobby: true,
 *         tags: {
 *             "string": "string"
 *         },
 *         maxPlayers: 1,
 *         captcha: {
 *             hcaptcha: {
 *                 clientResponse: "string"
 *             },
 *             turnstile: {
 *                 clientResponse: "string"
 *             }
 *         },
 *         verificationData: {
 *             "key": "value"
 *         }
 *     }
 */
export interface FindLobbyRequest {
    origin?: string;
    gameModes: string[];
    regions?: string[];
    preventAutoCreateLobby?: boolean;
    tags?: Record<string, string>;
    maxPlayers?: number;
    captcha?: Tivet.captcha.Config;
    verificationData?: unknown;
}
