/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tivet from "../../../../../../index";

/**
 * @example
 *     {
 *         lobbyId: "string",
 *         captcha: {
 *             hcaptcha: {
 *                 clientResponse: "string"
 *             },
 *             turnstile: {
 *                 clientResponse: "string"
 *             }
 *         },
 *         verificationData: {
 *             "key": "value"
 *         }
 *     }
 */
export interface JoinLobbyRequest {
    lobbyId: string;
    captcha?: Tivet.captcha.Config;
    verificationData?: unknown;
}
